/*
 * StatusCake API
 *
 * Copyright (c) 2022
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 * API version: 1.0.1
 * Contact: support@statuscake.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package statuscake

import (
	"encoding/json"
	"fmt"
)

// SSLTestCheckRate Number of seconds between checks
type SSLTestCheckRate int32

const (
	// SSLTestCheckRateFiveMinutes a check rate of 5 minutes.
	SSLTestCheckRateFiveMinutes SSLTestCheckRate = 300
	// SSLTestCheckRateTenMinutes a check rate of 10 minutes.
	SSLTestCheckRateTenMinutes SSLTestCheckRate = 600
	// SSLTestCheckRateThirtyMinutes a check rate of 30 minutes.
	SSLTestCheckRateThirtyMinutes SSLTestCheckRate = 1800
	// SSLTestCheckRateOneHour a check rate of 1 hour.
	SSLTestCheckRateOneHour SSLTestCheckRate = 3600
	// SSLTestCheckRateOneDay a check rate of 1 day.
	SSLTestCheckRateOneDay SSLTestCheckRate = 86400
	// SSLTestCheckRateOneWeek a check rate of 1 week.
	SSLTestCheckRateOneWeek SSLTestCheckRate = 2073600
)

// Unmarshal JSON data into any of the pointers in the type.
func (v *SSLTestCheckRate) UnmarshalJSON(src []byte) error {
	var value int32
	if err := json.Unmarshal(src, &value); err != nil {
		return err
	}

	ev := SSLTestCheckRate(value)
	if !ev.Valid() {
		return fmt.Errorf("%+v is not a valid SSLTestCheckRate", value)
	}

	*v = ev
	return nil
}

// Valid determines if the value is valid.
func (v SSLTestCheckRate) Valid() bool {
	return v == SSLTestCheckRateFiveMinutes || v == SSLTestCheckRateTenMinutes || v == SSLTestCheckRateThirtyMinutes || v == SSLTestCheckRateOneHour || v == SSLTestCheckRateOneDay || v == SSLTestCheckRateOneWeek
}

// SSLTestCheckRateValues returns the values of SSLTestCheckRate.
func SSLTestCheckRateValues() []int32 {
	return []int32{
		300,
		600,
		1800,
		3600,
		86400,
		2073600,
	}
}
