/*
 * StatusCake API
 *
 * Copyright (c) 2022
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 * API version: 1.0.1
 * Contact: support@statuscake.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package statuscake

import (
	"encoding/json"
	"time"
)

// UptimeTestPeriod struct for UptimeTestPeriod
type UptimeTestPeriod struct {
	// When the status period was created (RFC3339 format)
	Created time.Time `json:"created_at"`
	// Status period duration (ms)
	Duration *int64 `json:"duration,omitempty"`
	// When the status period ended (RFC3339 format)
	Ended  *time.Time       `json:"ended_at,omitempty"`
	Status UptimeTestStatus `json:"status"`
}

// NewUptimeTestPeriod instantiates a new UptimeTestPeriod object.
// This constructor will assign default values to properties that have it
// defined, and makes sure properties required by API are set, but the set of
// arguments will change when the set of required properties is changed.
func NewUptimeTestPeriod(createdAt time.Time, status UptimeTestStatus) *UptimeTestPeriod {
	return &UptimeTestPeriod{
		Created: createdAt,
		Status:  status,
	}
}

// MarshalJSON serialises data in the struct to JSON.
func (o UptimeTestPeriod) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["created_at"] = o.Created
	}
	if o.Duration != nil {
		toSerialize["duration"] = o.Duration
	}
	if o.Ended != nil {
		toSerialize["ended_at"] = o.Ended
	}
	if true {
		toSerialize["status"] = o.Status
	}
	return json.Marshal(toSerialize)
}
