/*
 * StatusCake API
 *
 * Copyright (c) 2023
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 * API version: 1.1.0
 * Contact: support@statuscake.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package statuscake

import (
	"encoding/json"
)

// PagespeedTestStats struct for PagespeedTestStats
type PagespeedTestStats struct {
	// Latest recorded filesize (kb)
	Filesize float32 `json:"filesize"`
	// Whether the latest check has an issue
	HasIssue bool `json:"has_issue"`
	// Latest recorded loadtime (ms)
	Loadtime int32 `json:"loadtime"`
	// Latest recorded request count
	Requests int32 `json:"requests"`
	// Latest recorded issue
	LatestIssue *string `json:"latest_issue,omitempty"`
}

// NewPagespeedTestStats instantiates a new PagespeedTestStats object.
// This constructor will assign default values to properties that have it
// defined, and makes sure properties required by API are set, but the set of
// arguments will change when the set of required properties is changed.
func NewPagespeedTestStats(filesize float32, hasIssue bool, loadtime int32, requests int32) *PagespeedTestStats {
	return &PagespeedTestStats{
		Filesize: filesize,
		HasIssue: hasIssue,
		Loadtime: loadtime,
		Requests: requests,
	}
}

// MarshalJSON serialises data in the struct to JSON.
func (o PagespeedTestStats) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["filesize"] = o.Filesize
	}
	if true {
		toSerialize["has_issue"] = o.HasIssue
	}
	if true {
		toSerialize["loadtime"] = o.Loadtime
	}
	if true {
		toSerialize["requests"] = o.Requests
	}
	if o.LatestIssue != nil {
		toSerialize["latest_issue"] = o.LatestIssue
	}
	return json.Marshal(toSerialize)
}
