/*
 * StatusCake API
 *
 * Copyright (c) 2022
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 * API version: 1.0.0-beta.2
 * Contact: support@statuscake.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package statuscake

import (
	"encoding/json"
)

// UptimeTestOverview struct for UptimeTestOverview
type UptimeTestOverview struct {
	// Uptime check ID
	ID string `json:"id"`
	// Name of the check
	Name string `json:"name"`
	// URL or IP address of the server under test
	WebsiteURL string              `json:"website_url"`
	TestType   UptimeTestType      `json:"test_type"`
	CheckRate  UptimeTestCheckRate `json:"check_rate"`
	// List of contact group IDs
	ContactGroups []string `json:"contact_groups"`
	// Whether the check should be run
	Paused bool             `json:"paused"`
	Status UptimeTestStatus `json:"status"`
	// List of tags
	Tags []string `json:"tags"`
	// Uptime percentage for a check
	Uptime *float32 `json:"uptime,omitempty"`
}

// NewUptimeTestOverview instantiates a new UptimeTestOverview object.
// This constructor will assign default values to properties that have it
// defined, and makes sure properties required by API are set, but the set of
// arguments will change when the set of required properties is changed.
func NewUptimeTestOverview(id string, name string, websiteUrl string, testType UptimeTestType, checkRate UptimeTestCheckRate, contactGroups []string, paused bool, status UptimeTestStatus, tags []string) *UptimeTestOverview {
	return &UptimeTestOverview{
		ID:            id,
		Name:          name,
		WebsiteURL:    websiteUrl,
		TestType:      testType,
		CheckRate:     checkRate,
		ContactGroups: contactGroups,
		Paused:        paused,
		Status:        status,
		Tags:          tags,
	}
}

// Marshal data from the in the struct to JSON.
func (o UptimeTestOverview) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.ID
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["website_url"] = o.WebsiteURL
	}
	if true {
		toSerialize["test_type"] = o.TestType
	}
	if true {
		toSerialize["check_rate"] = o.CheckRate
	}
	if true {
		toSerialize["contact_groups"] = o.ContactGroups
	}
	if true {
		toSerialize["paused"] = o.Paused
	}
	if true {
		toSerialize["status"] = o.Status
	}
	if true {
		toSerialize["tags"] = o.Tags
	}
	if o.Uptime != nil {
		toSerialize["uptime"] = o.Uptime
	}
	return json.Marshal(toSerialize)
}
