/*
 * StatusCake API
 *
 * Copyright (c) 2021 StatusCake
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 * API version: 1.0.0-beta.1
 * Contact: support@statuscake.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package statuscake

import (
	"encoding/json"
)

// ContactGroup struct for ContactGroup
type ContactGroup struct {
	// Contact group ID
	ID string `json:"id"`
	// Name of the contact group
	Name string `json:"name"`
	// URL or IP address of an endpoint to push uptime events. Currently this only supports HTTP GET endpoints
	PingURL *string `json:"ping_url,omitempty"`
	// List of email addresses
	EmailAddresses []string `json:"email_addresses"`
	// List of international format mobile phone numbers
	MobileNumbers []string `json:"mobile_numbers"`
	// List of configured integration IDs
	Integrations []string `json:"integrations"`
}

// NewContactGroup instantiates a new ContactGroup object.
// This constructor will assign default values to properties that have it
// defined, and makes sure properties required by API are set, but the set of
// arguments will change when the set of required properties is changed.
func NewContactGroup(id string, name string, emailAddresses []string, mobileNumbers []string, integrations []string) *ContactGroup {
	return &ContactGroup{
		ID:             id,
		Name:           name,
		EmailAddresses: emailAddresses,
		MobileNumbers:  mobileNumbers,
		Integrations:   integrations,
	}
}

func (o ContactGroup) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.ID
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.PingURL != nil {
		toSerialize["ping_url"] = o.PingURL
	}
	if true {
		toSerialize["email_addresses"] = o.EmailAddresses
	}
	if true {
		toSerialize["mobile_numbers"] = o.MobileNumbers
	}
	if true {
		toSerialize["integrations"] = o.Integrations
	}
	return json.Marshal(toSerialize)
}
