/*
 * StatusCake API
 *
 * Copyright (c) 2022
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 * API version: 1.0.0-beta.2
 * Contact: support@statuscake.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package backoff_test

import (
	"testing"
	"time"

	"github.com/StatusCakeDev/statuscake-go/backoff"
)

func TestConstant(t *testing.T) {
	t.Run("returns a constant duration", func(t *testing.T) {
		b := backoff.Constant{
			BaseDelay: 6.0 * time.Second,
		}

		retries := 5

		expected := b.BaseDelay
		got := b.Backoff(retries)

		if expected != got {
			t.Errorf("expected: %s, got: %s", expected, got)
		}
	})
}

func TestExponential(t *testing.T) {
	t.Run("returns the next duration in an exponential sequence", func(t *testing.T) {
		b := backoff.Exponential{
			backoff.Config{
				BaseDelay:  1.0 * time.Second,
				Multiplier: 2.0, // Exponential factor.
				Jitter:     0,   // To make test predictible.
				MaxDelay:   120 * time.Second,
			},
		}

		retries := 5

		expected := time.Duration(32 * time.Second)
		got := b.Backoff(retries)

		if expected != got {
			t.Errorf("expected: %s, got: %s", expected, got)
		}
	})

	t.Run("returns the base delay when there are no retries remaining", func(t *testing.T) {
		b := backoff.Exponential{
			backoff.Config{
				BaseDelay:  1.0 * time.Second,
				Multiplier: 2.0, // Exponential factor.
				Jitter:     0,   // To make test predictible.
				MaxDelay:   120 * time.Second,
			},
		}

		retries := 0

		expected := b.BaseDelay
		got := b.Backoff(retries)

		if expected != got {
			t.Errorf("expected: %s, got: %s", expected, got)
		}
	})

	t.Run("returns the maximum delay when the calculated backoff exceeds the maximum", func(t *testing.T) {
		b := backoff.Exponential{
			backoff.Config{
				BaseDelay:  1.0 * time.Second,
				Multiplier: 2.0, // Exponential factor.
				Jitter:     0,   // To make test predictible.
				MaxDelay:   120 * time.Second,
			},
		}

		retries := 7

		expected := b.MaxDelay
		got := b.Backoff(retries)

		if expected != got {
			t.Errorf("expected: %s, got: %s", expected, got)
		}
	})
}

func TestLinear(t *testing.T) {
	t.Run("returns the next duration in a linear sequence", func(t *testing.T) {
		b := backoff.Linear{
			backoff.Config{
				BaseDelay:  1.0 * time.Second,
				Multiplier: 1.0,
				Jitter:     0, // To make test predictible.
				MaxDelay:   120 * time.Second,
			},
		}

		retries := 5

		expected := time.Duration(5 * time.Second)
		got := b.Backoff(retries)

		if expected != got {
			t.Errorf("expected: %s, got: %s", expected, got)
		}
	})

	t.Run("returns the base delay when there are no retries remaining", func(t *testing.T) {
		b := backoff.Linear{
			backoff.Config{
				BaseDelay:  1.0 * time.Second,
				Multiplier: 1.0,
				Jitter:     0, // To make test predictible.
				MaxDelay:   120 * time.Second,
			},
		}

		retries := 0

		expected := b.BaseDelay
		got := b.Backoff(retries)

		if expected != got {
			t.Errorf("expected: %s, got: %s", expected, got)
		}
	})

	t.Run("returns the maximum delay when the calculated backoff exceeds the maximum", func(t *testing.T) {
		b := backoff.Linear{
			backoff.Config{
				BaseDelay:  1.0 * time.Second,
				Multiplier: 1.0,
				Jitter:     0, // To make test predictible.
				MaxDelay:   120 * time.Second,
			},
		}

		retries := 121

		expected := b.MaxDelay
		got := b.Backoff(retries)

		if expected != got {
			t.Errorf("expected: %s, got: %s", expected, got)
		}
	})
}
