name: lint
on:
  push:
  pull_request:

jobs:
  staticcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: dominikh/staticcheck-action@v1.2.0
      with:
        version: "2022.1.1"
