---
name: policy
on:
  pull_request:
  push:
    branches:
    - gh-readonly-queue/**
jobs:
  check-merge-commits:
    if: github.event_name == 'pull_request'
    name: Check merge commits
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: |
        git config --global --add safe.directory /github/workspace
        merge_commits=$(git rev-list --merges "origin/$GITHUB_BASE_REF".."origin/$GITHUB_HEAD_REF")
        if [ -n "$merge_commits" ]; then
          echo "Error: merge commits found in $GITHUB_BASE_REF..$GITHUB_HEAD_REF"
          for merge_commit in $merge_commits; do
            echo "$merge_commit"
          done
          exit 1
        fi
